### ISSUE TITLE
Mouse Events

### ISSUE THREAD

**Issue by Jossif** [willsoto/angular-chartist.js#110]
I searched through the available posts and got confused. Are any other events other than on('draw') supported ?

I'm trying to understand how to implement mouse event handling in my bar chart. Could someone give an example please ?

**Comment by willsoto** [comment]
Please see [here](https://gionkunz.github.io/chartist-js/api-documentation.html#chartistbase-function-on) and [here](https://gionkunz.github.io/chartist-js/examples.html)
