### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by hardzork** [willsoto/angular-chartist.js#117]
First, sorry for my english.. 

I have an angularjs application (v1.6.1) and when I try to apply in my project the following error occurs: 

`Uncaught SyntaxError: Unexpected token import`

what am I doing wrong?

I've already injected dependency into app.js and referenced the files in the correct order.

Can I use it on my project? I see in other directives a different way... for example, here is used this way:

```
Import angular from 'angular';
Import Chartist from 'chartist';
```

And in all the others, I see this way:

```
(Function () {
 'Use strict';

 Angular.module ('directive-name', []);
```

some help?

**Comment by willsoto** [comment]
Are you transpiling ES2015? It's clear the problem here is the `import` statement itself is not supported.

**Comment by hardzork** [comment]
Thanks!
