### ISSUE TITLE
[BUG] chartist-events are not optional

### ISSUE THREAD

**Issue by zentoaku** [willsoto/angular-chartist.js#135]
Hi,

if I don't provide something like chartist-events="{}" in the template, I'm getting:
`TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at AngularChartistCtrl.bindEvents (angular-chartist.js:98)
    at AngularChartistCtrl.renderChart (angular-chartist.js:118)
    at AngularChartistCtrl.update (angular-chartist.js:135)
    at Scope.$digest (angular.js:17836)
    at Scope.$apply (angular.js:18102)
    at done (angular.js:12082)
    at completeRequest (angular.js:12291)
    at XMLHttpRequest.requestLoaded (angular.js:12219)`

**Comment by willsoto** [comment]
As long as `events` are something falsy, [I have code](https://github.com/willsoto/angular-chartist.js/blob/master/src/angular-chartist.js#L13) that will default it to an object. What value are you passing?

**Comment by zentoaku** [comment]
As I've described, if the attribute chartist-events is not defined for tag I'm getting an error. So the value is undefined.

**Comment by willsoto** [comment]
Could you provide a failing test case?

**Comment by zentoaku** [comment]
I've very simple use case (below). There are more packages in project but none to really interfere with yours.

packages:
```
"angular": "~1.6.4",
"angular-chartist.js": "~4.3.1",
"chartist": "~0.11.0",
"chartist-plugin-legend": "~0.6.1"
```

HTML:

```
<chartist class="ct-chart" 
            chartist-data="ctrl.chartData"
            chartist-chart-options="ctrl.OrderListChartOptions"
            chartist-responsive-options="ctrl.OrderListChartResponsiveOptions"
            chartist-chart-type="Pie"></chartist>
```

Params:

ctrl.chartData:
```
{
  "DELIVERED": 36,
  "SUBMITTED": 34,
  "CANCELLED": 29
}
```

ctrl.OrderListChartOptions:
```
{
      plugins: [
        plugins.legend({
          position: 'bottom'
        })
      ],
      width: '100%',
      height: '250px',
      chartPadding: 20,
      classNames: {
        label: 'order-list-chart-label'
      }
    }
```

ctrl.OrderListChartResponsiveOptions:
```
[
      ['screen and (max-width: 480px)', {
        width: '100vw',
        height: '100vw',
        classNames: {
          label: 'order-list-chart-label mobile'
        }
      }]
    ]
```
