### ISSUE TITLE
Chartist should be a dependency (not dev dependency)

### ISSUE THREAD

**Issue by zentoaku** [willsoto/angular-chartist.js#136]
Projects that are using angular-chartist shouldn't care about dependencies of the dependencies so this lilb should have a strict depenedency defined in package.json for chartist and not to force developer to download and manage it on their own.

**Comment by willsoto** [comment]
Thanks for the suggestion. I'm gonna leave it as is though.

**Comment by zentoaku** [comment]
I'ts like "must have" for library or framework out there. There's basically no reason to not to do it in proper way.
