### ISSUE TITLE
when show hiding the line chart not working as expected

### ISSUE THREAD

**Issue by goutham-M** [willsoto/angular-chartist.js#16]
Initially I will hide the chart, after based one condition I want to show the chart at that time its not showing .After increasing or decreasing the window size line chart  will show.

**Comment by fzgharaei** [comment]
Got the same problem, fixed by giving initializing width & height in chart options. 
If you don't pass width & height in options it will use their value from defaultOptions which are predefined as undefined! 
By the way, tnx for great light weight lib :)

**Comment by paradox41** [comment]
Thanks! Glad you are enjoying it.
