### ISSUE TITLE
labels not displayed on chrome

### ISSUE THREAD

**Issue by despi8** [willsoto/angular-chartist.js#171]
I have created a line chart using chartist.js but the labels are not shown and displayed correctly, please do help... If anyone does know how to make it visible... or how we are able to display it.

**Comment by willsoto** [comment]
Have you added your labels like [this](https://github.com/willsoto/angular-chartist.js/blob/master/example/index.js#L37)? Did you load the CSS correctly? Are there styles that could be conflicting? 

Besides basic troubleshooting there is not a whole lot else I can do for you. If you've checked everything else, I'd suggest filing an issue [here](https://github.com/gionkunz/chartist-js)

**Comment by despi8** [comment]
how i can i make CSS better and use it in the my chart
