### ISSUE TITLE
Consider Renovate

### ISSUE THREAD

**Issue by rarkins** [willsoto/angular-chartist.js#175]
Hi @willsoto, thanks for this project. I use it in one of my repositories and noticed you are needing to do a lot of manual dependency update commits (e.g. for `rollup`). I have written a tool/service that would save you some time here: https://github.com/apps/renovate (source repository: https://github.com/renovateapp/renovate)

The main improvements it has versus your current solution is:
- Lock files are automatically included with each PR, no extra config necessary
- If a newer version of a dependency is released then the PR is updated in-place and lock file updated, instead of you needing to make your own PRs

**Comment by willsoto** [comment]
Appreciate the suggestion, but I've actually been happy with Greenkeeper. The reason I was having to do it manually is because I was being lazy 😅 

Thanks!

**Comment by rarkins** [comment]
OK, but in that case you should remove the `yarn.lock` and add it to `.gitignore` if you don't plan to really use it. A `yarn.lock` that does not match `package.json` is considered invalid and not a good idea to keep in a repository.
