### ISSUE TITLE
chartist doesnt draw on first load when using API data

### ISSUE THREAD

**Issue by gotters** [willsoto/angular-chartist.js#240]
If i use static data the chart loads fine. If I load data via an API it doesnt draw any chart.
If I switch the page dimensions (via chrome dev tools) then it redraws and displays.
Any idea why this might be happening?

Also I wanted to try and call the Chartist API but not sure how to do that when using via angular-chartist?

**Comment by willsoto** [comment]
Check out the [example with async data](https://github.com/willsoto/angular-chartist.js/blob/master/example/index.js#L19)

**Comment by gotters** [comment]
I don't see anything special happening there that would force a redraw. Is there a way to directly access the chartist api so that I can call update on the chart?

**Comment by willsoto** [comment]
The redraw happens [here](https://github.com/willsoto/angular-chartist.js/blob/master/src/angular-chartist.js#L20-L32) when something changes. Can you paste me some code?

**Comment by gotters** [comment]
This is my code that fetches the data and tries to rebuild the chart information

As you can see I am updating both the labels and the series but the chart remains either empty or displays the original static data it was loaded with.
My current workaround is to call the chart.update() as I am doing at the last part of the code below

Let me know if you see any issue. Based on your code just updating the data should trigger a redraw but its not.


```
this.getHealthData().subscribe((data:any) => {
      console.log('healthdata',data);  
       if(data && data.length > 0) {
         this.chart.data.series = [];
         this.chart.data.labels = [];
         let sys = [];
         let dia = [];
         let lbls = [];
         
         _.forEach(data,(bp,index) => {

            let lbl = moment(bp.userOccurredOn + 'Z').format('DD-MM');
            if(lbls.indexOf(lbl) == -1) {
              lbls.push(lbl);
              sys.push(bp.data.systolic);
              dia.push(bp.data.diastolic);
            }

         });
         this.chart.data.labels = lbls;
         this.chart.data.series.push(sys);
         this.chart.data.series.push(dia);
         console.log(this.chart.data);

         //not sure how else to do this for now
         var chartDom = document.getElementById("historychart");
         if(chartDom && chartDom["__chartist__"])
            chartDom["__chartist__"]["update"]();
       }
       
    },  err => {
      console.error('ERROR', err);
    });
```

**Comment by gotters** [comment]
I think I have fixed it....I see your $watch is watchign the chart.data. Instead of just updating the data.labels and data.series I am now updating the whole data object and that seems to trigger the redraw.
Thanks for the help

**Comment by willsoto** [comment]
Yup. You beat me to it, I was about to suggest the same thing. Glad you got it working.
