### ISSUE TITLE
Distributed Series Some Bars Are Not Visible

### ISSUE THREAD

**Issue by rlkmert** [willsoto/angular-chartist.js#508]
I am using the bar chart. When the number of labels is greater than 15, the bars do not appear and reappear on the 27th label. The sample code on the official site is the same. Help me, please. I am sure you will understand better in the pictures.
![Mycahart](https://user-images.githubusercontent.com/54894474/73427858-c92b8400-4348-11ea-8b0b-8bcaa16d25c5.PNG)
![OfficalChart](https://user-images.githubusercontent.com/54894474/73427928-ee1ff700-4348-11ea-828b-6044bc4a122e.PNG)

**Comment by willsoto** [comment]
Seems like something you should report to the [Chartist repo](https://github.com/gionkunz/chartist-js) since this library has no control over how charts render.
